# Generated by Django 4.2.5 on 2023-10-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrak_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
